---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME="inmotionhosting.wordpress_ultrastack"
    - ROLE_DIR="/home/travis/.ansible/roles"
    - GIT_BASE="https://github.com/inmotionhosting"
  matrix:
    - MOLECULE_DISTRO="centos-7"
    - MOLECULE_DISTRO="centos-8"
    - MOLECULE_DISTRO="debian-9"
    - MOLECULE_DISTRO="debian-10"
    - MOLECULE_DISTRO="ubuntu-16.04"
    - MOLECULE_DISTRO="ubuntu-18.04"

addons:
  apt:
    packages:
      - git
      - python3-pip

install:
  - pip install ansible ansible-lint docker molecule[docker] testinfra yamllint
  - ansible-galaxy install inmotionhosting.{apache,mysql,php_fpm,nginx_proxy,redis} -p $ROLE_DIR

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME inmotionhosting.$ROLE_NAME
  - cd inmotionhosting.$ROLE_NAME

script:
  - molecule test
  - molecule test --scenario-name ultrastack

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
