---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME="inmotion.wordpress-ultrastack"
    - ROLE_DIR="/home/travis/build/inmotionhosting/inmotion.wordpress-ultrastack/molecule/default/roles"
    - GIT_BASE="https://github.com/inmotionhosting"
  matrix:
    - MOLECULE_DISTRO="centos-7"
    - MOLECULE_DISTRO="centos-8"
    - MOLECULE_DISTRO="debian-9"
    - MOLECULE_DISTRO="debian-10"
    - MOLECULE_DISTRO="ubuntu-16.04"
    - MOLECULE_DISTRO="ubuntu-18.04"

addons:
  apt:
    packages:
      - git
      - python3-pip

install:
  - pip install ansible docker molecule[docker] testinfra
  - ansible --version
  - molecule --version
  - ROLE="inmotion.apache" git clone $GIT_BASE/$ROLE $ROLE_DIR/$ROLE
  - ROLE="inmotion.mysql" git clone $GIT_BASE/$ROLE $ROLE_DIR/$ROLE
  - ROLE="inmotion.php-fpm" git clone $GIT_BASE/$ROLE $ROLE_DIR/$ROLE
  - ROLE="inmotion.nginx-proxy" git clone $GIT_BASE/$ROLE $ROLE_DIR/$ROLE
  - ROLE="inmotion.redis" git clone $GIT_BASE/$ROLE $ROLE_DIR/$ROLE

script:
  - molecule test
  - molecule test --scenario-name ultrastack

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
