---
os: linux
arch: amd64
dist: focal
services: docker
language: python

addons:
  apt:
    packages:
      - python3-pip

env:
  global:
    - GIT_BASE="https://github.com/inmotionhosting"
    - ROLE_DIR="/home/travis/.ansible/roles"
  matrix:
    - MOLECULE_DISTRO="centos-7"
    - MOLECULE_DISTRO="centos-8"
    - MOLECULE_DISTRO="debian-9"
    - MOLECULE_DISTRO="debian-10"
    - MOLECULE_DISTRO="ubuntu-16.04"
    - MOLECULE_DISTRO="ubuntu-18.04"
    - MOLECULE_DISTRO="ubuntu-20.04"

install:
  - pip install -r requirements.txt
  - git clone $GIT_BASE/ansible-role-apache $ROLE_DIR/ansible-role-apache
  - git clone $GIT_BASE/ansible-role-mysql $ROLE_DIR/ansible-role-mysql
  - git clone $GIT_BASE/ansible-role-php_fpm $ROLE_DIR/ansible-role-php_fpm
  - git clone $GIT_BASE/ansible-role-letsencrypt $ROLE_DIR/ansible-role-letsencrypt
  - git clone $GIT_BASE/ansible-role-wordpress $ROLE_DIR/ansible-role-wordpress
  - git clone $GIT_BASE/ansible-role-nginx_proxy $ROLE_DIR/inmotionhosting.nginx_proxy
  - git clone $GIT_BASE/ansible-role-redis $ROLE_DIR/inmotionhosting.redis

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
