---
- name: (Debian) Disable Apache mpm_event module
  apache2_module:
    name: "mpm_event"
    state: absent
    ignore_configcheck: true
  failed_when:
    - result.rc is defined
    - result.rc > 0
  register: result

- name: (Debian) Disable Apache PHP module
  apache2_module:
    name: "php{{ php_version }}"
    state: absent
    ignore_configcheck: true
  failed_when:
    - result.rc is defined
    - result.rc > 0
  register: result

- name: (Debian) Disable Apache mpm_prefork module
  apache2_module:
    name: "mpm_prefork"
    state: absent
    ignore_configcheck: true
  failed_when:
    - result.rc is defined
    - result.rc > 0
  register: result

- name: (Debian) Enable Apache mpm_worker module
  apache2_module:
    name: "mpm_worker"
    state: present
    ignore_configcheck: true
  failed_when:
    - result.rc is defined
    - result.rc > 0
  register: result

- name: (Debian) Enable Apache proxy_http module
  apache2_module:
    name: "proxy_http"
    state: present
    ignore_configcheck: true
  failed_when:
    - result.rc is defined
    - result.rc > 0
  register: result
