---
- name: (UltraStack) Set and sanitize facts
  set_fact:
    nginx_ratelimit_enable: >-
      {{ nginx_ratelimit_enable
      if nginx_ratelimit_paths is defined and
      nginx_ratelimit_paths | length > 0 and
      nginx_ratelimit_burst is defined and
      nginx_ratelimit_burst > 0 and
      nginx_ratelimit_nodelay is defined and
      nginx_ratelimit_zone is defined and
      nginx_ratelimit_zone | length > 0
      else "nginx_ratelimit_enable" }}
    php_proc_mem: >-
      {{ php_proc_mem
      if php_proc_mem is defined and
      php_proc_mem > 0
      else php_proc_mem }}
