---
- name: (LetsEncrypt) Install Certbot.
  package:
    name: certbot
    state: present

- name: (LetsEncrypt) Set Certbot script variable.
  set_fact:
    certbot_script: "certbot"

- name: (LetsEncrypt) Check if certificate already exists.
  stat:
    path: "/etc/letsencrypt/live/{{ site_domain }}/cert.pem"
  register: letsencrypt_cert

# TODO: Using failed_when here isn't a good idea.  Switch to updating
# the list of services based on use_ultrastack.
- name: (LetsEncrypt) Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  failed_when: false
  when: not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_stop_services }}"

- name: (LetsEncrypt) Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists

# TODO: Using failed_when here isn't a good idea.  Switch to updating
# the list of services based on use_ultrastack.
- name: (LetsEncrypt) Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  failed_when: false
  when: not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_stop_services }}"
