---
- name: Converge
  hosts: all
  roles:
    - role: inmotionhosting.apache
    - role: inmotionhosting.php_fpm
    - role: inmotionhosting.mysql
    - role: inmotionhosting.wordpress_ultrastack
      vars:
        use_letsencrypt: false
        use_ultrastack: false
