---
- name: Converge
  hosts: all
  roles:
    - role: inmotion.apache
    - role: inmotion.php-fpm
    - role: inmotion.mysql
    - role: inmotion.wordpress-ultrastack
      vars:
        use_letsencrypt: false
        use_ultrastack: false
